// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Provide a safe fallback during build so TypeScript doesn't error
    // on undefined environment variables (Vercel build-time can omit secrets).
    url: process.env["DATABASE_URL"] ?? "",
  },
});
